version: "3.9"

services:

  postgres:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_DB: url_shortener_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: redis_cache
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./backend
    container_name: spring_backend
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
    container_name: angular_frontend
    depends_on:
      - backend
    ports:
      - "4200:80"